# This file is used by the Thunderstore CLI to build and publish to Thunderstore. https://github.com/thunderstore-io/thunderstore-cli

[config]
schemaVersion = "0.0.1"

[package]
namespace = "eia485"
name = "SlotlessInspectorOpener"
versionNumber = "1.2.0"
description = "pressing the open inspector button on a refeditor targeting a worker that has no slot will now open it's parent worker. adds view parent on valid worker inspectors"# max 250 characters
websiteUrl = "http://github.com/EIA485/NeosSlotlessInspectorOpener"
containsNsfwContent = false

[package.dependencies] 
ResoniteModding-BepisLoader = "1.3.1"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

# Copy the compiled DLL to the plugins folder in mod package
[[build.copy]]
source = "SlotlessInspectorOpener/bin/Release/net9.0/SlotlessInspectorOpener.dll"
target = "plugins/"

# Include PDB
[[build.copy]]
source = "SlotlessInspectorOpener/bin/Release/net9.0/SlotlessInspectorOpener.pdb"
target = "plugins/"

# include LICENSE file in mod package
[[build.copy]]
source = "license.txt"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["resonite"]

[publish.categories]
resonite = [ "mods", "inspectors" ] # https://thunderstore.io/api/experimental/community/resonite/category/